[package]
name = "freertos_bundler"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
edition = "2018"


[dependencies]

# to select a stm32 family, use one of the following as the default
[features]
stm32f3x = []
stm32f4x = []
stm32f7x = []
stm32h7x = []
